name: Auto-standardize catalog on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'infores_catalog.yaml'

permissions:
  contents: write
  pull-requests: write

jobs:
  standardize:
    # Skip forks
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (no separate venv)
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi

      - name: Run standardization
        run: make standardize-data

      - name: Check for changes
        id: git-check
        run: |
          if git diff --quiet -- infores_catalog.yaml; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit and push if changed
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add infores_catalog.yaml
          git commit -m "Auto-standardize infores_catalog.yaml"
          git push
